# Generated by Django 4.2.2 on 2023-07-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_apis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apisl', models.IntegerField()),
                ('apikey', models.CharField(max_length=50)),
                ('api_value', models.CharField(max_length=50)),
                ('api_details', models.CharField(max_length=200)),
                ('api_type', models.CharField(max_length=15)),
                ('request_body', models.CharField(max_length=300)),
            ],
        ),
    ]
